import 'package:mini_fiverr/models/chat_model.dart';
import 'package:mini_fiverr/models/message_model.dart';
import 'package:mini_fiverr/models/notification_model.dart';
import 'package:mini_fiverr/models/professional_model.dart';
import 'package:mini_fiverr/models/security_question_model.dart';

class DemoData {
  static List<ProfessionalModel> get professionals => <ProfessionalModel>[
        const ProfessionalModel(
          id: 'pro_1',
          name: 'Alexandra Mitchell',
          title: 'Senior UI/UX Designer',
          hourlyRate: 65,
          rating: 4.9,
          reviewCount: 237,
          skills: <String>['UI Design', 'UX Research', 'Figma', 'Prototyping'],
          bio: 'Award-winning designer focused on modern interfaces and conversion-driven user journeys.',
          photoUrl: '',
          availability: 'Available',
          experience: '7 years',
          previousCompany: 'DesignLab Inc.',
          lookingFor: <String>['Remote', 'Full-Time'],
          isOnline: true,
        ),
        const ProfessionalModel(
          id: 'pro_2',
          name: 'Marcus Lee',
          title: 'Full-Stack Web Developer',
          hourlyRate: 58,
          rating: 4.8,
          reviewCount: 191,
          skills: <String>['Web Dev', 'React', 'Node.js', 'APIs'],
          bio: 'Builds high-performance platforms with clean architecture and strong product thinking.',
          photoUrl: '',
          availability: 'Available',
          experience: '6 years',
          previousCompany: 'CloudForge',
          lookingFor: <String>['Remote'],
          isOnline: true,
        ),
        const ProfessionalModel(
          id: 'pro_3',
          name: 'Priya Narang',
          title: 'Mobile App Engineer',
          hourlyRate: 62,
          rating: 4.7,
          reviewCount: 156,
          skills: <String>['Mobile', 'Flutter', 'iOS', 'Android'],
          bio: 'Ships polished mobile experiences with strong performance and delightful motion.',
          photoUrl: '',
          availability: 'Available',
          experience: '5 years',
          previousCompany: 'AppPulse',
          lookingFor: <String>['Remote', 'Part-Time'],
          isOnline: true,
        ),
        const ProfessionalModel(
          id: 'pro_4',
          name: 'Daniel Hart',
          title: 'SEO Growth Specialist',
          hourlyRate: 49,
          rating: 4.6,
          reviewCount: 121,
          skills: <String>['SEO', 'Analytics', 'Content Strategy'],
          bio: 'Improves traffic, retention, and discoverability for fast-growing digital products.',
          photoUrl: '',
          availability: 'Available',
          experience: '8 years',
          previousCompany: 'RankPilot',
          lookingFor: <String>['Remote'],
          isOnline: false,
        ),
        const ProfessionalModel(
          id: 'pro_5',
          name: 'Bianca Reyes',
          title: 'Content Strategist',
          hourlyRate: 41,
          rating: 4.8,
          reviewCount: 173,
          skills: <String>['Content', 'Copywriting', 'Brand Voice'],
          bio: 'Creates high-converting content systems with clear voice and measurable impact.',
          photoUrl: '',
          availability: 'Available',
          experience: '6 years',
          previousCompany: 'Wordcraft Studio',
          lookingFor: <String>['Remote', 'Full-Time'],
          isOnline: true,
        ),
        const ProfessionalModel(
          id: 'pro_6',
          name: 'Noah Kim',
          title: 'Graphic Designer',
          hourlyRate: 44,
          rating: 4.7,
          reviewCount: 140,
          skills: <String>['Design', 'Branding', 'Illustration'],
          bio: 'Designs premium visual systems, logos, and product graphics with sharp storytelling.',
          photoUrl: '',
          availability: 'Available',
          experience: '5 years',
          previousCompany: 'Pixel Avenue',
          lookingFor: <String>['Part-Time', 'Remote'],
          isOnline: false,
        ),
        const ProfessionalModel(
          id: 'pro_7',
          name: 'Sarah Johnston',
          title: 'Data Scientist',
          hourlyRate: 72,
          rating: 4.9,
          reviewCount: 102,
          skills: <String>['Data', 'Python', 'ML', 'Dashboards'],
          bio: 'Builds data models and decision tools that turn complexity into clear actions.',
          photoUrl: '',
          availability: 'Available',
          experience: '7 years',
          previousCompany: 'InsightCore',
          lookingFor: <String>['Remote'],
          isOnline: true,
        ),
        const ProfessionalModel(
          id: 'pro_8',
          name: 'Ethan Cole',
          title: 'Cybersecurity Engineer',
          hourlyRate: 79,
          rating: 4.8,
          reviewCount: 88,
          skills: <String>['Security', 'Cloud', 'DevSecOps'],
          bio: 'Hardens applications and infrastructure with practical, modern security workflows.',
          photoUrl: '',
          availability: 'Available',
          experience: '9 years',
          previousCompany: 'SecureGrid',
          lookingFor: <String>['Remote', 'Full-Time'],
          isOnline: true,
        ),
      ];

  static List<ConversationModel> get conversations => <ConversationModel>[
        ConversationModel(
          id: 'conv_1',
          meId: '',
          otherUserId: 'pro_1',
          otherUserName: 'Alexandra Mitchell',
          otherUserAvatar: '',
          isOtherOnline: true,
          messages: <MessageModel>[
            MessageModel(
              id: 'm1',
              senderId: 'pro_1',
              content: 'Hello! Thanks for reaching out about your dashboard project.',
              timestamp: DateTime.now().subtract(const Duration(minutes: 28)),
              isSentByMe: false,
              isRead: false,
            ),
            MessageModel(
              id: 'm2',
              senderId: 'me',
              content: 'Hi! Yes, I need a modern dashboard design',
              timestamp: DateTime.now().subtract(const Duration(minutes: 26)),
              isSentByMe: true,
              isRead: true,
            ),
            MessageModel(
              id: 'm3',
              senderId: 'pro_1',
              content: 'Sounds good! Can you share more details about the requirements?',
              timestamp: DateTime.now().subtract(const Duration(minutes: 24)),
              isSentByMe: false,
              isRead: false,
            ),
          ],
        ),
      ];

  static List<NotificationModel> get notifications => <NotificationModel>[
        NotificationModel(
          id: 'notif_1',
          title: 'New message',
          body: 'Alexandra Mitchell sent you a message',
          previewText: 'Sounds good! Can you share more details?',
          timestamp: DateTime.now().subtract(const Duration(hours: 2)),
          type: NotificationType.message,
          isRead: false,
          relatedConversationId: 'conv_1',
        ),
        NotificationModel(
          id: 'notif_2',
          title: 'Request accepted',
          body: 'John Doe accepted your hire request',
          timestamp: DateTime.now().subtract(const Duration(hours: 5)),
          type: NotificationType.hireAccepted,
          isRead: false,
        ),
      ];

  static List<SecurityQuestionModel> get defaultSecurityQuestions =>
      const <SecurityQuestionModel>[
        SecurityQuestionModel(question: 'What is your pet name?', answer: ''),
        SecurityQuestionModel(question: 'What city were you born in?', answer: ''),
      ];
}
